In [6]:
import torch
a = torch.tensor([[1, 2, 3, 4, 5, 11], [6, 7, 8, 9, 0, 22]])
print(a.shape)

torch.Size([2, 6])


In [2]:
print(a)

tensor([[ 1,  2,  3,  4,  5, 11],
        [ 6,  7,  8,  9,  0, 22]])


In [10]:
c=a[:,0::2]
d=a[:,1::2]

print(a[:, 0::2])
print(a[:, 1::2])
print(a[:,0::2].shape)

tensor([[1, 3, 5],
        [6, 8, 0]])
tensor([[ 2,  4, 11],
        [ 7,  9, 22]])
torch.Size([2, 3])


In [8]:
b=torch.stack([a[:, 0::2], a[:, 1::2]], dim=0)
print(b)
print(b.shape)

tensor([[[ 1,  3,  5],
         [ 6,  8,  0]],

        [[ 2,  4, 11],
         [ 7,  9, 22]]])
torch.Size([2, 2, 3])


In [11]:
e=torch.concat([c,d],dim=0)
print(e)
print(e.shape)

tensor([[ 1,  3,  5],
        [ 6,  8,  0],
        [ 2,  4, 11],
        [ 7,  9, 22]])
torch.Size([4, 3])
